# Site settings
title: Reel Movement Blog
email: info@reelmovement.com
description: > # this means to ignore newlines until "baseurl:"
  check out my blog
twitter_username: reelmovement
fb_appid:    1063835490346190     
baseurl: "/blog"
paginate: 4
exclude:
  - 'config.ru'
  - 'gemfile'
  - 'gemfile.lock'
  - 'vendor'






# Build settings
markdown: kramdown
permalink: /:title


#default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Daniel Ponce
      layout: "post"
      category: articles
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
