# Site settings
title: Reel Movement Blog
email: danponce718@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This Blog is here to answer all your fitness needs. Do you live in the Brooklyn or queens area. Then shoot me and email and we can set up a complementary session. Do you have some fitness questions? Follow me on social media and ask away.
twitter_username: reelmovement
facebook_username:  reelmovement
instagram_username: coach_daniel0311

fb_appid:    1063835490346190     
baseurl: "/blog"
paginate: 4
exclude:
  - 'config.ru'
  - 'gemfile'
  - 'gemfile.lock'
  - 'vendor'






# Build settings
markdown: kramdown
permalink: /:title


#default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Daniel Ponce
      layout: "post"
      category: articles
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
