# Site settings
title: Reel Movement Blog
email: info@reelmovement.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: reelmovement
baseurl: "/blog"
paginate: 3
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']





# Build settings
markdown: kramdown
permalink: /:title


#default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Daniel Ponce
      layout: "post"
      category: articles
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
